services:
  mail-stock-valuator:
    build:
      context: ./mail-valuator
      dockerfile: Dockerfile

    volumes:
      - /var/cache/mail-valuator:/app/data
      - /var/log/mail-valuator:/app/logs

    # environment:
    #   - IMAP_HOST=imap.gmail.com
    #   - IMAP_USER=${USER}
    #   - SMTP_PORT=587
    #   - IMAP_PASSWD=${PASSWD}
    #   - SMTP_HOST=smtp.gmail.com