services:
  web-stock-valuator:
    build:
      context: ./backend

    ports:
      - "5000:5000"

    volumes:
      - ./backend:/app

    environment:
      - FLASK_ENV=development

  mail-stock-valuator:
    build:
      context: ./mail-valuator
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    volumes:
      - ./mail-valuator:/app
    
    environment:
      - IMAP_HOST=imap.gmail.com
      - SMTP_PORT=587
      - IMAP_PASSWD=senha
      - SMTP_HOST=smtp.gmail.com