services:
  mail-stock-valuator:
    build:
      context: ./mail-valuator
      dockerfile: Dockerfile

    volumes:
      - ./mail-valuator/data:/app/data
      - ./mail-valuator/logs:/app/logs

    # environment:
    #   - IMAP_HOST=imap.gmail.com
    #   - IMAP_USER=${USER}
    #   - SMTP_PORT=587
    #   - IMAP_PASSWD=${PASSWD}
    #   - SMTP_HOST=smtp.gmail.com