services:
  web-stock-valuator-front:
    build:
      context: ./frontent

    ports:
      -"8001:8001"
      

  web-stock-valuator:
    build:
      context: ./backend

    ports:
      - "5000:5000"

    volumes:
      - ./backend:/app
    
    # environment:
    #   - IMAP_HOST=imap.gmail.com
    #   - IMAP_USER=${USER}
    #   - SMTP_PORT=587
    #   - IMAP_PASSWD=${PASSWD}
    #   - SMTP_HOST=smtp.gmail.com