name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start with Docker Compose
        run: docker compose up -d --build

      - name: Show running containers
        run: docker ps

      # Opcional: derruba os containers após a build
      - name: Tear down containers
        run: docker compose down
